[Database]
host="127.0.0.1"
port=3306
database="minecraft"
username="minecraft"
password="minecraft"
[Messages]
StandardBanMessage="The ban hammer has spoken!"
StandardKickMessage="Kicked by an operator!"
BanLayout="§4§lBANNED:§r\n§aUntil: $bannedUntil§r\n§3Reason: §r§b$reason§r\n§cBanned by: $bannedBy§r"
KickLayout="§4§lYou got kicked:\n §r$reason"